name: Build & deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**' # Only consider paths directly relevant to the build
      - 'README.md'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Set up cache
        uses: actions/cache@v6
        with:
          path: ${{ env.HUGO_CACHEDIR }} # <- Use the same env variable just right here
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build website with Hugo
        run: |
          echo "Building the project..."
          hugo build \
            --gc \
            --minify
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v5
        with:
          name: build-artifact
          path: public/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: build-artifact
